# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Steph Brooks
tagline:          'Technical Writer & Web Developer'
description:      'Hi! I'm a technical writer and web developer based in San Francisco, CA. Welcome to my portfolio site! <a href="#">Contact Me</a>'
url:              https://stephbrooks.com
baseurl:          /

author:
  name:           'Stephanie Brooks'
  url:            https://stephbrooks.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sbro/sbro.github.io
