# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            SBRO
tagline:          'A Jekyll Site'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://sbro.github.io
baseurl:          https://sbro.github.io

author:
  name:           'Stephanie Brooks'
  url:            https://stephbrooks.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sbro/sbro.github.io
